data:
  run_id: 0
  antimicrobial: "vancomycin"
  labels: "data/ast_labels.csv"
  root_dir: "data/extracted_unitigs"
  input_dir: "${data.root_dir}"
  id_root_dir: "data"
  whole_ids: "${data.id_root_dir}/whole.ids"
  val_ids: "${data.id_root_dir}/val.ids"
  train_ids: "${data.id_root_dir}/train.ids"
  predict_ids: "${data.id_root_dir}/predict.ids"  
  test_ids: "${data.id_root_dir}/${data.run_id}/${data.antimicrobial}_predict.ids"
  retaining_pmille: 2
  use_decoupling: False
  use_class_weight: True
  decoupling_matrix: "/pvol/data/mlst_decoupling_mat.csv"
  no_edge: False
  save_adj_matrix: False

adj_matrix:
  use_precompute_matrix: True
  file_path_1: "data/fcgr_adj_matrix.csv"
  file_path_2: "data/snps_adj_matrix.csv"

gnn:
  model_name: "GNN"
  layer_name: "GCN"
  use_feature_encoder: False
  num_layers: 2
  c_hidden: 128
  c_out: 1
  dp_rate: 0.5
  middle_layer: "low_rank_fusion"
  GAT:
    heads: 8
  TransformerConv:
    heads: 8
  lmf:
    rank: 4

trainer:
  seed: 222
  default_root_dir: "experiments"
  max_epochs: 200
  accelerator: "auto"
  devices: "auto"
  accumulate_grad_batches: 1
  num_nodes: 1
  strategy: "auto"
  precision: 32
  model_checkpoint:
    dirpath: "${trainer.default_root_dir}/out/${trainer.logger.project_prefix}_${trainer.logger.name_prefix}/${data.antimicrobial}/${data.run_id}/"
    monitor: "val_loss"
    mode: "min"
    save_last: False
    save_top_k: 1
  logger:
    save_dir: "${trainer.default_root_dir}/logger/${data.antimicrobial}/${data.run_id}"
    project_prefix: "multi_wgs"
    project: "${trainer.logger.project_prefix}_${data.antimicrobial}"
    name_prefix: "6mer"
    name: "${trainer.logger.name_prefix}_${data.run_id}"
  del_ckpt: False

prediction:
  outdir: "${trainer.model_checkpoint.dirpath}"
